model:
  target: model.Restormer.Restormer_inp_concat
  params:
    inp_channels: 1
    out_channels: 1

training:
  name: Restormer_inp_concat_0102
  max_epoch: 100
  batch_size: 4
  initial_lr: 0.0001
  val_interval: 1
  ckpt_save_dir: Results/Restormer
  loss_type: torch.nn.MSELoss
  wrapper: model.wrapper.BaseModelWrapper

data:
  dataset: dataset.DynamicMRIDataset
  img_train_dir: Dataset/Multix4/train/center
  img_val_dir: Dataset/Multix4/val/center

test:
  dataset: dataset.MRIDataset
  img_test_dir: Dataset/Multix4/test
  result_dir: Results/Restormer/inferTs

log:
  project: MRI-Reconstruction
  log_dir: Logs/Restormer

experiment_goal: "DCL training compared with input concat on Multix4"
